const books = [
    {
      id: 1,
      title: "Belajar JavaScript Dasar",
      author: "Andi Prasetyo",
      year: 2021,
      description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
      image: "https://example.com/images/js-dasar.jpg",
    },
    {
      id: 2,
      title: "React untuk Pemula",
      author: "Dina Sari",
      year: 2022,
      description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
      image: "https://example.com/images/react-pemula.jpg",
    },
    {
      id: 3,
      title: "Mastering CSS",
      author: "Budi Setiawan",
      year: 2020,
      description: "Pelajari teknik-teknik styling modern dengan CSS dan framework populer.",
      image: "https://example.com/images/css-master.jpg",
    },
    {
      id: 4,
      title: "Node.js Lanjutan",
      author: "Rina Kurnia",
      year: 2023,
      description: "Bangun backend yang efisien menggunakan Node.js dan Express.",
      image: "https://example.com/images/nodejs.jpg",
    },
    {
      id: 5,
      title: "Database MySQL",
      author: "Eka Putra",
      year: 2019,
      description: "Pelajari query dasar dan lanjutan dalam pengelolaan database MySQL.",
      image: "https://example.com/images/mysql.jpg",
    },
    {
      id: 6,
      title: "UI/UX Design Basics",
      author: "Tania Wijaya",
      year: 2021,
      description: "Panduan mendesain antarmuka pengguna yang menarik dan fungsional.",
      image: "https://example.com/images/uiux.jpg",
    },
    {
      id: 7,
      title: "Git & Version Control",
      author: "Arif Nugroho",
      year: 2020,
      description: "Pahami cara kerja Git dan kolaborasi tim dalam pengembangan proyek.",
      image: "https://example.com/images/git.jpg",
    },
    {
      id: 8,
      title: "Fullstack Web Development",
      author: "Siti Hasanah",
      year: 2023,
      description: "Gabungkan kemampuan frontend dan backend dalam satu buku lengkap.",
      image: "https://example.com/images/fullstack.jpg",
    },
    {
      id: 9,
      title: "Belajar TypeScript",
      author: "Daniel Surya",
      year: 2022,
      description: "Menjadi mahir menggunakan TypeScript dalam pengembangan web modern.",
      image: "https://example.com/images/typescript.jpg",
    },
  ];
  
  export default books;
  